### ISSUE TITLE
A Well Written and Documented Package That Does Not Install or Run Correctly In Multiple Contexts

### ISSUE THREAD

**Issue by lvwarren** [MelJan/PyDeep#6] opened 2021-10-12 11:33 UTC
I really appreciated the examples and well-written package documented at https://pydeep.readthedocs.io/
I am running:
- iMac: Retina 5K, 27-inch, Late 2015
-- OS: macOS BigSur 11.6
-- Processor: 3.2 GHz Quad-Core Intel Core i5
-- Memory: 32 GB 1867 MHz DDR3
-- Graphics: AMD Radeon R9 M390 2 GB
-  Anaconda:  4.10.3
-  Python 3.8.11
- Jupyter Notebook Server:  4.10.3

I run deep learning codes.
I installed pydeep according to the instructions:
```bash
# Download PyDeep from GitHub/MelJan
unzip PyDeep-master.zip
cd PyDeep-master
python setup.py install
```
but it will not run the unit tests:
```bash
python -m unittest discover -s testunits
```

It rather produced the following output:
```
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
...
  File "/Applications/anaconda3/lib/python3.8/unittest/loader.py", line 346, in discover
    raise ImportError('Start directory is not importable: %r' % start_dir)
ImportError: Start directory is not importable: 'testunits'
```
Before attempting the direct code install I had attempted to load PyDeep into my Anaconda environment using
```bash
conda install pydeep
```
but it is not recognized by conda, so I used pip
```bash
pip install pydeep
```
but. this created serious compile-time conflicts with _pyobjc_ that took a night of debugging and a complete reinstall of anaconda to solve.
This may have been due to the recent Big Sur upgrade of October 11, 2021 by Apple.
I eventually solved this issue using a beta of _pyobjc_ as follows:
```bash
pip install pyobjc-core==8.0b1
pip install pyobjc-framework-Cocoa==8.0b1
pip install pyobjc-framework-Quartz==8.0b1
```

Anyway I am presenting the obstacles I encountered in reverse order in the hope that your 2017 package can remain viable for its quality construction and clarity.
In the meantime I will use sklearn PCA, which is much less elegant than your streamlined implementation.

**Comment by MelJan** [comment] 2021-10-17 20:13
Dear Ivwarren,

sorry for the late reply, I could not manage to reply earlier.

Regarding your pyobj problems: 
Thanks for the input  bbut I a pretty sure this is not a pydeep problem as it is written purely in python (no C compilation or others) and has only two strict dependencies (numpy, scipy), and one optional (matplotlib). So I guess the problem was caused by a conflict of either numpy and/or scipy with your installation. Once numpy and scipy are working it pydeep has to function properly.
So as you pointed out this seems to be a python+mac problem rather than a pydeep problem.

Regarding conda: Pydeep is not a registered package, so conda does not know pydeep and you have to use pip.
 
Regarding unittest: Thanks for pointing this out, I will fix that on the weekend, unittest require now that the test module is importable. 
For the tie being navigate into PyDeep/pydeep/testunits
and run 
python -m unittest discover -s .
should work.
running all unit test easly take an hour, so you can only run the preprocessing unitstests to speedup.

Let me know if you need further help

Best Jan.

**Comment by lvwarren** [comment] 2021-10-18 03:59
Per your instructions:

(tf) van pydeep [516]: python --version
Python 3.7.11
(tf) van pydeep [520]: pwd
/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep
(tf) van pydeep [517]: python -m unittest discover -s .

EEEEEEEEEEEEEEEEE
======================================================================
ERROR: testunits.test_ae.test_model (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_ae.test_model
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_ae/test_model.py", line 37, in <module>
    from pydeep.misc.toyproblems import generate_bars_and_stripes_complete
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_ae.test_sae (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_ae.test_sae
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_ae/test_sae.py", line 37, in <module>
    import pydeep.ae.sae as STACK
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_ae.test_trainer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_ae.test_trainer
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_ae/test_trainer.py", line 37, in <module>
    from pydeep.misc.toyproblems import generate_bars_and_stripes_complete
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_base.test_activationfunction (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_base.test_activationfunction
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_base/test_activationfunction.py", line 37, in <module>
    from pydeep.base.activationfunction import *
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_base.test_basicstructure (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_base.test_basicstructure
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_base/test_basicstructure.py", line 42, in <module>
    from pydeep.base.activationfunction import Sigmoid
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_base.test_corruptor (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_base.test_corruptor
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_base/test_corruptor.py", line 37, in <module>
    from pydeep.base.corruptor import *
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_base.test_costfunction (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_base.test_costfunction
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_base/test_costfunction.py", line 36, in <module>
    from pydeep.base.costfunction import *
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_base.test_numpyextension (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_base.test_numpyextension
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_base/test_numpyextension.py", line 37, in <module>
    from pydeep.base.numpyextension import *
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_fnn.test_layer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_fnn.test_layer
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_fnn/test_layer.py", line 35, in <module>
    from pydeep.fnn.layer import FullConnLayer
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_fnn.test_model (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_fnn.test_model
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_fnn/test_model.py", line 35, in <module>
    from pydeep.fnn.layer import FullConnLayer
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_fnn.test_trainer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_fnn.test_trainer
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_fnn/test_trainer.py", line 35, in <module>
    from pydeep.fnn.layer import FullConnLayer
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_preprocessing (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_preprocessing
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_preprocessing.py", line 40, in <module>
    from pydeep.base.numpyextension import get_norms, angle_between_vectors
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_rbm.test_dbn (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_rbm.test_dbn
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_rbm/test_dbn.py", line 39, in <module>
    import pydeep.rbm.dbn as STACK
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_rbm.test_estimator (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_rbm.test_estimator
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_rbm/test_estimator.py", line 39, in <module>
    from pydeep.misc.toyproblems import generate_bars_and_stripes_complete
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_rbm.test_model (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_rbm.test_model
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_rbm/test_model.py", line 40, in <module>
    from pydeep.misc.toyproblems import generate_bars_and_stripes_complete
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_rbm.test_sampler (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_rbm.test_sampler
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_rbm/test_sampler.py", line 39, in <module>
    from pydeep.misc.toyproblems import generate_bars_and_stripes_complete
ModuleNotFoundError: No module named 'pydeep'


======================================================================
ERROR: testunits.test_rbm.test_trainer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: testunits.test_rbm.test_trainer
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/anaconda3/envs/tf/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/van/Dropbox/Software/VanPhD/ipynb/PyDeep-master/pydeep/testunits/test_rbm/test_trainer.py", line 39, in <module>
    from pydeep.misc.toyproblems import generate_bars_and_stripes_complete
ModuleNotFoundError: No module named 'pydeep'


----------------------------------------------------------------------
Ran 17 tests in 0.001s

FAILED (errors=17)

________________________________

**Comment by MelJan** [comment] 2021-10-18 20:33
-> ModuleNotFoundError: No module named 'pydeep'
-> the package is not installed, eithet install it or add its location to the path variable

**Comment by MelJan** [comment] 2022-01-17 19:12
As the error is not related to PyDeep, but due to Mac & pyobjc I am closing this issue.

**Closed by MelJan** 2022-01-17 19:12 UTC
